### ISSUE TITLE
项目分类建议

### ISSUE THREAD

**Issue by ZiHAO-LI-cmd** [Global-CS-application/global-cs-application.github.io#23]
建议欧陆项目列表以国家分类，基于录取难度比较主观且每年情况不同，比如今年23fall，Aalto CS/MLDSAI的Bar明显上升。

**Comment by Lee-abcde** [comment]
欧洲国家太多了难以分类。
我们添加一个文章专门表述了我们划分方面的标准
https://global-cs-application.github.io/Program/search/

**Comment by Lee-abcde** [comment]
Aalto项目我已经提升上来了，谢谢建议
