### ISSUE TITLE
申请QQ群已满

### ISSUE THREAD

**Issue by Lynchrocket** [Global-CS-application/global-cs-application.github.io#83]
【加入我们】页面的qq群似乎满人了，请问还有其他群可以加嘛？或者请问有考虑使用qq频道或者discord等其他的嘛？（似乎这两个不限制人数？）

**Comment by Lee-abcde** [comment]
我试着创建了一个discord服务器，邀请链接[https://discord.com/invite/HqFPthjr](url)。
我不太会弄这个，先尝试一下。
感谢提醒。
